version: "3.7"

services:
  dev_db:
    image: postgres:15
    container_name: pg_rinha
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_DB=rinha_dev
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./priv/support/create_test_db.sql:/docker-entrypoint-initdb.d/1-schema.sql
